site_name: WaveON
site_description: DocumentaÃ§Ã£o WAVEon
site_url: https://mdsreq-fga-unb.github.io/2025.2-T01-WaveOn
repo_url: https://github.com/mdsreq-fga-unb/2025.2-T01-WaveOn
repo_name: mdsreq-fga-unb/2025.2-T01-WaveOn
edit_uri: edit/docs/docs/

nav:

  - InÃ­cio: index.md  
  - VisÃ£o do produto e Projeto:
      - 1. CenÃ¡rio Atual do Cliente e do NegÃ³cio: visao_produto/cenario_atual.md
      - 2. SoluÃ§Ã£o Proposta: visao_produto/solucao_proposta.md
      - 3. EstratÃ©gias de Engenharia de Software: visao_produto/estrategias.md
      - 4. Engenharia de Requisitos: visao_produto/engenharia_requisitos.md
      - 5. Cronogramas e Entregas: visao_produto/cronograma_entregas.md
      - 6. InteraÃ§Ã£o Entre Equipe e Cliente: visao_produto/interacao_equipe.md
      - 7. Requisitos de Software: visao_produto/requisitos_software.md
      - 8. DoR e DoD: visao_produto/dod_dor.md
      - 9. Backlog de Produto: visao_produto/backlog_produto.md
      - 10. LiÃ§Ãµes Aprendidas: visao_produto/licoes_aprendidas.md
      - 11. ReferÃªncias BibliogrÃ¡ficas: visao_produto/bibliografia.md

  #- Fases & Backlogs:

  - Entregas: 
      - Entrega Unidade 1:
          - Video de apresentaÃ§Ã£o: entregas/video_unidade_1.md

  - PolÃ­ticas da Equipe:
      - PolÃ­tica de Commit: politicas_equipe/commits.md
      - PolÃ­tica de Branch: politicas_equipe/branches.md
      - PolÃ­tica de Issue: politicas_equipe/issues.md
      - PolÃ­tica de Pull Request(PR): politicas_equipe/pull_request.md

#      - Proposta:
#          - ğŸš€ Objetivos do produto: Proposta/objetivos.md
#          - ğŸ§© CaracterÃ­sticas da SoluÃ§Ã£o: Proposta/caracteristicas_solucao.md
#          - ğŸ’° Pesquisa de Mercado e AnÃ¡lise Competitiva: Proposta/pesquisa_mercado.md
#          - ğŸ” AnÃ¡lise de Viabilidade: Proposta/analise_viabilidade.md
#          - âš–ï¸ Impacto da SoluÃ§Ã£o: Proposta/impacto_solucao.md
#          - ğŸ“• EstratÃ©gia Priorizada: Proposta/estrategia_priorizada.md
#      - Planejamento:
#          - âœ’ Quadro Comparativo: Planejamento/quadro_comparativo.md
#          - ğŸ›ï¸ Justificativa: Planejamento/justificativa.md
#          - ğŸ“… Cronograma e Entregas: Planejamento/cronograma_entregas.md
#          - ğŸ”ˆ ComunicaÃ§Ã£o: Planejamento/comunicacao.md
#          - âœ… Processo de ValidaÃ§Ã£o: Planejamento/processo_validacao.md
#      - Equipe:
#          - ğŸ˜ ComposiÃ§Ã£o de Equipe: Equipe/composicao_equipe.md
#      - Unidade 1:
#          - 1ï¸âƒ£ Unidade um: Unidade 1/unidade_um.md
#      - Requisitos De Software:
#          - ğŸ› ï¸ Requisitos Funcionais(RF): Requisitos/requisitos_funcionais.md
#          - ğŸ”’ Requisitos NÃ£o-Funcionais(RNF): Requisitos/requisitos_nao_funcionais.md
#      - Guias Boas PrÃ¡ticas:
#          - ğŸ’¾ Commit: Guias/commits.md
#          - ğŸŒ³ Branch: Guias/branches.md
#          - ğŸš© Issue: Guias/issues.md
#          - ğŸ”ƒ Pull Request(PR): Guias/pull_request.md

theme:
  name: material
  language: pt-BR

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - footer.copyright
    - footer.social

  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb/2025.2-T01-WaveOn
    - icon: fontawesome/brands/twitter
      link: https://x.com/mdsreq-fga-unb
  copyright: "2025, Grupo 7 - WaveON"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
