site_name: WaveON 
site_description: DocumentaÃ§Ã£o WAVEon
site_url: https://mdsreq-fga-unb.github.io/2025.2-T01-WaveOn
repo_url: https://github.com/mdsreq-fga-unb/2025.2-T01-WaveOn
repo_name: mdsreq-fga-unb/2025.2-T01-WaveOn
edit_uri: edit/main/docs/

nav:
  - InÃ­cio: index.md
  - Produto:
    - ğŸ” IdentificaÃ§Ã£o da Oportunidade: identificacao_oportunidade.md
    - ğŸ§— Desafios do Projeto: desafios.md
    - ğŸ¯ SegmentaÃ§Ã£o de Clientes: segmentacao_clientes.md
    - ğŸš€ Objetivos do produto: objetivos.md
    - ğŸ§© CaracterÃ­sticas da SoluÃ§Ã£o: caracteristicas_solucao.md
    - ğŸ’° Pesquisa de Mercado e AnÃ¡lise Competitiva: pesquisa_mercado.md
    - ğŸ” AnÃ¡lise de Viabilidade: analise_viabilidade.md
    - âš–ï¸ Impacto da SoluÃ§Ã£o: impacto_solucao.md
    - ğŸ“• EstratÃ©gia Priorizada: estrategia_priorizada.md
    - âœ’ Quadro Comparativo: quadro_comparativo.md
    - ğŸ›ï¸ Justificativa: justificativa.md
    - ğŸ“… Cronograma e Entregas: cronograma_entregas.md
    - ğŸ˜ ComposiÃ§Ã£o de Equipe: composicao_equipe.md
    - ğŸ”ˆ ComunicaÃ§Ã£o: comunicacao.md
    - âœ… Processo de ValidaÃ§Ã£o: processo_validacao
    - 1ï¸âƒ£ Unidade um: unidade_um.md
    
  
  

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb
    - icon: fontawesome/brands/twitter
      link: https://x.com/mdsreq-fga-unb
