site_name: WaveON
site_description: DocumentaÃ§Ã£o WAVEon
site_url: https://mdsreq-fga-unb.github.io/2025.2-T01-WaveOn
repo_url: https://github.com/mdsreq-fga-unb/2025.2-T01-WaveOn
repo_name: mdsreq-fga-unb/2025.2-T01-WaveOn
edit_uri: edit/main/docs/

nav:
  - InÃ­cio: Nav/index.md
  - Produto:
      - DiagnÃ³stico:
          - ğŸ” IdentificaÃ§Ã£o da Oportunidade: DiagnÃ³stico/identificacao_oportunidade.md
          - ğŸ§— Desafios do Projeto: DiagnÃ³stico/desafios.md
          - ğŸ¯ SegmentaÃ§Ã£o de Clientes: DiagnÃ³stico/segmentacao_clientes.md
      - Proposta:
          - ğŸš€ Objetivos do produto: Proposta/objetivos.md
          - ğŸ§© CaracterÃ­sticas da SoluÃ§Ã£o: Proposta/caracteristicas_solucao.md
          - ğŸ’° Pesquisa de Mercado e AnÃ¡lise Competitiva: Proposta/pesquisa_mercado.md
          - ğŸ” AnÃ¡lise de Viabilidade: Proposta/analise_viabilidade.md
          - âš–ï¸ Impacto da SoluÃ§Ã£o: Proposta/impacto_solucao.md
          - ğŸ“• EstratÃ©gia Priorizada: Proposta/estrategia_priorizada.md
      - Planejamento:
          - âœ’ Quadro Comparativo: Planejamento/quadro_comparativo.md
          - ğŸ›ï¸ Justificativa: Planejamento/justificativa.md
          - ğŸ“… Cronograma e Entregas: Planejamento/cronograma_entregas.md
          - ğŸ”ˆ ComunicaÃ§Ã£o: Planejamento/comunicacao.md
          - âœ… Processo de ValidaÃ§Ã£o: Planejamento/processo_validacao.md
      - Equipe:
          - ğŸ˜ ComposiÃ§Ã£o de Equipe: Equipe/composicao_equipe.md
      - Unidade 1:
          - 1ï¸âƒ£ Unidade um: Unidade 1/unidade_um.md

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdsreq-fga-unb
    - icon: fontawesome/brands/twitter
      link: https://x.com/mdsreq-fga-unb
