site_name: "WaveON"
site_description: Documentação WAVEon
site_url: https://mdsreq-fga-unb.github.io/2025.2-T01-WaveOn
repo_url: https://github.com/mdsreq-fga-unb/2025.2-T01-WaveOn
repo_name: mdsreq-fga-unb/2025.2-T01-WaveOn
edit_uri: edit/docs/docs/

nav:

  - Início: index.md  
  - Visão do produto e Projeto:
      - 1. Cenário Atual do Cliente e do Negócio: visao_produto/cenario_atual.md
      - 2. Solução Proposta: visao_produto/solucao_proposta.md
      - 3. Estratégias de Engenharia de Software: visao_produto/estrategias.md
      - 4. Engenharia de Requisitos: visao_produto/engenharia_requisitos.md
      - 5. Cronogramas e Entregas: visao_produto/cronograma_entregas.md
      - 6. Interação Entre Equipe e Cliente: visao_produto/interacao_equipe.md
      - 7. Requisitos de Software: visao_produto/requisitos_software.md
      - 8. DoR & DoD: visao_produto/dod_dor.md
      - 9. Backlog de Produto: backlog/backlog.md
      - 10. Lições Aprendidas e Melhorias para o Processo: visao_produto/licoes_aprendidas.md
      - 11. Referências Bibliográficas: visao_produto/bibliografia.md

  - Ciclos & Backlog:
      - 9.Backlog Geral: backlog/backlog.md

  - Entregas:
      - Entregas das Unidades: entregas/video_unidades.md
      #- Entregas Cilente(Cronograma):

  - Políticas da Equipe:
      - Política de Commit: politicas_equipe/commits.md
      - Política de Branch: politicas_equipe/branches.md
      - Política de Issue: politicas_equipe/issues.md
      - Política de Pull Request(PR): politicas_equipe/pull_request.md

theme:
  name: material
  language: pt-BR
  logo: img/logo_aba.png
  favicon: img/logo_aba.png

  font:
    text: Roboto
    code: Roboto Mono

  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition

extra_css:
  - stylesheets/extra.css